### ISSUE TITLE
Makefile doesn't work anymore since 18.10.0

### ISSUE THREAD

**Issue by stephankusch** [WeAreFairphone/modem_zip_generator#11]
Even after fitting in the new filename scheme, version and checksum the makefile halts in line 93, probably because of a changed ota-zip file topology. Haven't figured out what exactly happened (late night on a Sunday). The manual zip for Fairphone Open hasn't changed regarding its structure, however. After inspecting the relevant image files updating the modem_zip-generator should be worth it.

**Comment by z3ntu** [comment]
Created a PR - #12
