### ISSUE TITLE
Error 6 with 18.10.0 Edify binary and current updater-script

### ISSUE THREAD

**Issue by Roboe** [WeAreFairphone/modem_zip_generator#13]
Using `update-binary` from `18.10.0-sibon-280f64b0-ota.zip` causes the following error in TWRP:

```
Installing zip file '/sideload/package.zip'
Updater process ended with ERROR: 6"
```

However, it works just great with the 18.04.1 one (`fp2-sibon-18.04.1-ota-userdebug.zip`). This may mean our `updater-script` is not compatible with some new syntax for Oreo's [Edify](https://source.android.com/devices/tech/ota/nonab/inside_packages), so we should keep this in mind for future releases.

As a temporary measure, we can just release it with 18.04.1's Edify.

**Comment by Ingo-FP-Angel** [comment]
It seems only the first line in the script needs to change. I've taken it from the 19.02.1 OTA ZIP and was able to build and flash a new modem.zip (see PR #14).

**Comment by Roboe** [comment]
Aaaah! Seems like the newer Edify interpreters don't include the `get_device_compatible` function. Great!

Thanks, Ingo! :D
