### ISSUE TITLE
Build is not reproducible

### ISSUE THREAD

**Issue by htgoebel** [WeAreFairphone/modem_zip_generator#15]
When building a release on my machine, I get bfd0d11a465b46d52a5276f84a1231c408e2a45651e575d236b7451c679df0ce  modem-19.11.2_2020-05-30.zip
while the version downloaded from https://github.com/WeAreFairphone/modem_zip_generator/releases/tag/19.11.2 has 2320ed28dd7dc34407c7ed55bd5a5e976aef0ca6a54f9c71efbbb6e185efb091  modem-19.11.2_2020-02-11.zip

If builds are "reproducible", I would expect both zip archives have the same checksum. (Having different file-names would be okay IMHO.)

**Comment by z3ntu** [comment]
Can you please upload your zip and/or run the tool "diffoscope" with the two zips to compare what's different?
When running `make build` on my system I'm getting a zip with the sha256 hash of 2320ed28dd7dc34407c7ed55bd5a5e976aef0ca6a54f9c71efbbb6e185efb091

**Comment by htgoebel** [comment]
Thanks to diffoscope I found out: File permissions differed.
Adding this line to the Makefile solved the issue
```
	@$(FIND) "$(TEMP_DIR)" -type f -exec chmod u=rw,go=r {} + # Reproducibility
```
(no ime for a pull-request, thoug.
