### ISSUE TITLE
Added OSX support, but checksum mismatch

### ISSUE THREAD

**Issue by jfdhuiz** [WeAreFairphone/modem_zip_generator#4]
Hi,

I added OSX support to modem.sh.

I searched and replaced sha256sum to $sha256sum

In line 12 I added:

if test `uname` == Darwin ; then sha256sum=gsha256sum ; else sha256sum=sha256sum; fi

To use, one needs to install GNU coreutils. Using Homebrew: $ brew install coreutils

Result:

$ gsha256sum modem-17.12.1.zip
d89abda5950d5feda0474a6b4d0122a514da4c58cc212a55ec009666863293ba  modem-17.12.1.zip

On WSL (Windows Subsystem for Linux) it worked out of the box with Ubuntu. However I got the following result:

$ sha256sum modem-17.12.1.zip
dfeb89ed50371b768f2b656d97c4a489dedb7631ef56a6af4484e2097aac2d36  modem-17.12.1.zip

**Comment by jannispinter** [comment]
Cool, thank you for your work! 

I guess `zip` on OSX works a bit different as it does on Linux, therefore producing a slightly different file. We could try using `bsdtar` to create the zip file instead, which is available for both Linux and OSX.

Edit: Could you try zipping the same file on OSX and Linux and compare the hashes?
Edit2: I'm not able to get reproducible hashes on Linux either.

**Comment by jannispinter** [comment]
After searching the web for `reproducible zip` I found an interessting [article](https://content.pivotal.io/blog/barriers-to-deterministic-reproducible-zip-files).

I'll try to modify the modem.sh script in a way that it creates reproducible files. Thanks for bringing this up, as I naively assumed zip would be deterministic.

**Comment by jfdhuiz** [comment]
Sorry something went wrong with the formatting. Let me retry. On line 12, I added:

`if test ``uname`` == Darwin ; then sha256sum=gsha256sum ; else sha256sum=sha256sum; fi`

I guess I can't make an [grave accent](https://en.wikipedia.org/wiki/Grave_accent) for some reason... uname should be surrounded in that. EDIT: now I got 2 instead of 1... I give up.

I tried again on 3 different machines (Linux (Debian 8.10), macOS (10.13.3), Windows (WSL/Ubuntu)).

I keep getting different sha256sums, with every try.

But also, you might wanna look into securely writing in /tmp. I recommend to check umask (or set it) and then use a random generated hash in /tmp so that other users cannot guess it. Cause, for example, the Linux machine I used is a semi-public shell (my ISP's).

**Comment by jannispinter** [comment]
> But also, you might wanna look into securely writing in /tmp. I recommend to check umask (or set it) and then use a random generated hash in /tmp so that other users cannot guess it. Cause, for example, the Linux machine I used is a semi-public shell (my ISP's).

Good point! I will implement this in the coming days together with other security measures and a bit of cleanup.

**Comment by jfdhuiz** [comment]
If you prefer to use GNU Tar a macOS user can install it via $ brew install gnu-tar
It can then be executed via gtar

But zip and BSD tar should also work.

As for deterministic builds I read through your linked article (which further links to another general website). Maybe you can use https://github.com/wolfcw/libfaketime to get uniform dates.

I just swapped to the examples of GNU tar as mentioned on reproducible-builds.org:

$tar --sort=name  --mtime="@${SOURCE_DATE_EPOCH}" --owner=0 --group=0 --numeric-owner -cf "$CURRENT_DIR/modem-$VERSION.tar" META-INF/* firmware-update/*

However @${SOURCE_DATE_EPOCH} doesn't work on my Linux machine (it does work on macOS). So I went with:

$tar --sort=name --mtime='2015-10-21 00:00Z' --clamp-mtime --owner=0 --group=0 --numeric-owner -cf "$CURRENT_DIR/modem-$VERSION.tar" META-INF/* firmware-update/*

and for

if test ``uname`` == Darwin ; then sha256sum=gsha256sum ; tar=gtar ; else sha256sum=sha256sum; tar=tar; fi

(With one grave accent)

And right under that I added:

umask 0077

I echoed gtar/tar -tvf modem*.tar to m1.txt and m2.txt and diffed it. The result is this:
```

3d2
< -rw------- 0/0            1240 2015-07-09 09:12 META-INF/MANIFEST.MF
12c11
< -rw-r--r-- 0/0        58967552 2015-10-21 02:00 firmware-update/NON-HLOS.bin
---
> -rw------- 0/0            1240 2015-07-09 09:12 META-INF/MANIFEST.MF
13a13
> -rw-r--r-- 0/0        58967552 2015-10-21 02:00 firmware-update/NON-HLOS.bin

```
Close, but no dice. However the good news is that its locally deterministic with the above. But the order of MANIFEST.MF is always the bloody same on these machines, yet different between them.

**Comment by jannispinter** [comment]
I have added OSX support, although slightly different than suggested. On Linux, I am now able to get reproducible builds. Could you test it on OSX?

Thank you for all your suggestions! 👍

**Comment by jfdhuiz** [comment]
I get:

./modem.sh: line 27: sha256sum: command not found

On macOS I get:

7d038b7fb2d0776f5a9dc07782922fcc3ec37edf03d7f3987cfb320e28a20fb9  modem-18.02.0.zip

On WSL/Ubuntu I get:

82241f31cd8d7b4346df832f4ccc3934100f7c6a64d0c3ea31bc79a1a29cb41c  modem-18.02.0.zip

I did unzip -v modem-18.02.0.zip and verified the contents with a diff of the outputs. It has the very same problem I had with tar: the order of the files is different. The CRC32 check.

```
1,17c1,17
<     1552  Defl:N     1157  26% 01-01-2014 00:00 347ec90d  META-INF/CERT.RSA
<     1428  Defl:N      641  55% 01-01-2014 00:00 d4b76d3a  META-INF/CERT.SF
<     1240  Defl:N      614  51% 01-01-2014 00:00 30924015  META-INF/MANIFEST.MF
<        0  Stored        0   0% 01-01-2014 00:00 00000000  META-INF/com/
<        0  Stored        0   0% 01-01-2014 00:00 00000000  META-INF/com/google/
<        0  Stored        0   0% 01-01-2014 00:00 00000000  META-INF/com/google/android/
<     1091  Defl:N      381  65% 01-01-2014 00:00 5eba02a5  META-INF/com/google/android/updater-script
<   619420  Defl:N   398450  36% 01-01-2014 00:00 d98728d6  META-INF/com/google/android/update-binary
<        0  Stored        0   0% 01-01-2014 00:00 00000000  META-INF/com/android/
<     1452  Defl:N      942  35% 01-01-2014 00:00 bf91f1d2  META-INF/com/android/otacert
<      210  Defl:N      115  45% 01-01-2014 00:00 05a127ae  META-INF/com/android/metadata
< 58967552  Defl:N 32203055  45% 01-01-2014 00:00 d3d69c24  firmware-update/NON-HLOS.bin
<   536648  Defl:N   101236  81% 01-01-2014 00:00 5aec0c92  firmware-update/emmc_appsboot.mbn
<   191388  Defl:N    97692  49% 01-01-2014 00:00 fa54966e  firmware-update/rpm.mbn
<   280936  Defl:N   162592  42% 01-01-2014 00:00 b7db3a69  firmware-update/sbl1.mbn
<  6221312  Defl:N    30575 100% 01-01-2014 00:00 28a51ac6  firmware-update/splash.img
<   342344  Defl:N   180383  47% 01-01-2014 00:00 f21b2da3  firmware-update/tz.mbn
---
>     1552  Defl:N     1157  26% 2014-01-01 00:00 347ec90d  META-INF/CERT.RSA
>     1428  Defl:N      641  55% 2014-01-01 00:00 d4b76d3a  META-INF/CERT.SF
>        0  Stored        0   0% 2014-01-01 00:00 00000000  META-INF/com/
>        0  Stored        0   0% 2014-01-01 00:00 00000000  META-INF/com/android/
>      210  Defl:N      115  45% 2014-01-01 00:00 05a127ae  META-INF/com/android/metadata
>     1452  Defl:N      942  35% 2014-01-01 00:00 bf91f1d2  META-INF/com/android/otacert
>        0  Stored        0   0% 2014-01-01 00:00 00000000  META-INF/com/google/
>        0  Stored        0   0% 2014-01-01 00:00 00000000  META-INF/com/google/android/
>   619420  Defl:N   398450  36% 2014-01-01 00:00 d98728d6  META-INF/com/google/android/update-binary
>     1091  Defl:N      381  65% 2014-01-01 00:00 5eba02a5  META-INF/com/google/android/updater-script
>     1240  Defl:N      614  51% 2014-01-01 00:00 30924015  META-INF/MANIFEST.MF
>   536648  Defl:N   101236  81% 2014-01-01 00:00 5aec0c92  firmware-update/emmc_appsboot.mbn
> 58967552  Defl:N 32203055  45% 2014-01-01 00:00 d3d69c24  firmware-update/NON-HLOS.bin
>   191388  Defl:N    97692  49% 2014-01-01 00:00 fa54966e  firmware-update/rpm.mbn
>   280936  Defl:N   162592  42% 2014-01-01 00:00 b7db3a69  firmware-update/sbl1.mbn
>  6221312  Defl:N    30575 100% 2014-01-01 00:00 28a51ac6  firmware-update/splash.img
>   342344  Defl:N   180383  47% 2014-01-01 00:00 f21b2da3  firmware-update/tz.mbn
```

**Comment by Roboe** [comment]
Ok, thing is not reproducible yet. I'm getting this output after the Make migration:

Input:
```
make clean build && mv build/modem.zip build/modem.zip.1
make clean build && mv build/modem.zip build/modem.zip.2
diffoscope build/modem.zip.1 build/modem.zip.2
```
Output:
<details>
<summary>Click to enlarge</summary>

```
$ diffoscope build/modem.zip.1 build/modem.zip.2 
 |##########################################################################################################################################|  100%                             Time: 0:00:03 
--- build/modem.zip.1
+++ build/modem.zip.2
├── zipinfo /dev/stdin
│ @@ -1,15 +1,15 @@
│  Zip file size: 33182944 bytes, number of entries: 13
│  drwxr-xr-x  3.0 unx        0 b- stor 18-Jun-06 02:21 META-INF/
│  drwxr-xr-x  3.0 unx        0 b- stor 18-Jun-06 02:21 META-INF/com/
│  drwxr-xr-x  3.0 unx        0 b- stor 18-Jun-06 02:21 META-INF/com/google/
│ -drwxr-xr-x  3.0 unx        0 b- stor 18-Jun-08 01:43 META-INF/com/google/android/
│ --rw-r--r--  3.0 unx   623616 b- defN 18-Jun-08 01:43 META-INF/com/google/android/update-binary
│ +drwxr-xr-x  3.0 unx        0 b- stor 18-Jun-08 01:44 META-INF/com/google/android/
│ +-rw-r--r--  3.0 unx   623616 b- defN 18-Jun-08 01:44 META-INF/com/google/android/update-binary
│  -rw-r--r--  3.0 unx     1079 t- defN 18-Jun-07 21:22 META-INF/com/google/android/updater-script
│ -drwxr-xr-x  3.0 unx        0 b- stor 18-Jun-08 01:43 firmware-update/
│ +drwxr-xr-x  3.0 unx        0 b- stor 18-Jun-08 01:44 firmware-update/
│  -rw-r--r--  3.0 unx   342344 b- defN 15-Dec-03 15:50 firmware-update/tz.mbn
│  -rw-r--r--  3.0 unx   280944 b- defN 15-Dec-03 15:50 firmware-update/sbl1.mbn
│  -rw-r--r--  3.0 unx   547124 b- defN 15-Dec-03 15:50 firmware-update/emmc_appsboot.mbn
│  -rw-r--r--  3.0 unx  6221312 b- defN 15-Dec-03 15:50 firmware-update/splash.img
│  -rw-r--r--  3.0 unx 58967552 b- defN 15-Dec-03 15:50 firmware-update/NON-HLOS.bin
│  -rw-r--r--  3.0 unx   191452 b- defN 15-Dec-03 15:50 firmware-update/rpm.mbn
│  13 files, 67175423 bytes uncompressed, 33181284 bytes compressed:  50.6%
```
(with terminal colors it looks definitely better)
</details><br>

Diffoscope is just an amazing tooling. With an amazingly long list of dependencies too, haha.

The issue is dates, as pointed above. One of the date difference is my fault (4af12171f9a2de82171a0b02263b3acbb4caa86e) but the creation of the `firmware-update/` folder is another story.

**Comment by Roboe** [comment]
Got it in d6d8d86dc24dc12741c31842b6b523453fbdd91a! 😎

```
$ make release
Release file: './build/modem.zip' -> 'release/modem-18.04.1_2018-06-08.zip'
Release checksum: release/modem-18.04.1_2018-06-08.zip.sha256sum
$ cat release/modem-18.04.1_2018-06-08.zip.sha256sum 
8259ea621bf5808c08b14e164355259ff8ddee283632cfd537915a5dae09fd21  modem-18.04.1_2018-06-08.zip
```

Can somebody test this in OS X?

**Edit:** I tested on a Ubuntu machine and the ZIP has file sorting differences. Damned ZIP, :cry:. Well, at least is locally reproducible...

**Comment by jfdhuiz** [comment]
$ make release
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
Downloading fp2-sibon-18.04.1-ota-userdebug.zip...
######################################################################## 100.0%
/bin/bash: check: command not found
Unpacking firmware files...
unzip:  cannot find or open ./updates/fp2-sibon-18.04.1-ota-userdebug.zip, ./updates/fp2-sibon-18.04.1-ota-userdebug.zip.zip or ./updates/fp2-sibon-18.04.1-ota-userdebug.zip.ZIP.
make: *** [src/firmware-update] Error 9

**Comment by jfdhuiz** [comment]
mktemp -> gmktemp (on macOS)

**Comment by Roboe** [comment]
BTW, we are not going to get a cross-platform reproducible ZIP. What's right now is the best we can get, and what a reproducible build means, anyway:

> Second, the set of tools used to perform the build and more generally the build environment should either be recorded or pre-defined.

https://reproducible-builds.org/#how

We could config a CI system to build and publish each release with a predefined Docker image (e.g. Debian Stretch, [94.1% reproducible](https://tests.reproducible-builds.org/debian/reproducible.html)). That way anyone will have the recipe to verify it.
